### ISSUE TITLE
error "no eventdetection" 

### ISSUE THREAD

**Issue by mht85** [mateidavid/nanocall#10]
Hi,

I am hoping to basecall a large number of fast5 files online in order to bypass having to upload to Metrichor given the slow speed of internet. However, I'm having trouble getting results from the files using Nanocall (log message below).

= main.2 nanocall.cpp:846 main program: nanocall
= main.2 nanocall.cpp:847 main version: v0.5.13
= main.2 nanocall.cpp:848 main args: mumgf_PC_20160914_FNFAB29733_MN17852_sequencing_run_FAB29733test7_11420_ch261_read10340_strand1.fast5
= main.2 nanocall.cpp:849 main num_threads=1
= main.2 nanocall.cpp:911 main train=1
= main.2 nanocall.cpp:914 main only_train=0
= main.2 nanocall.cpp:915 main train_scaling=1
= main.2 nanocall.cpp:916 main train_transitions=1
= main.2 nanocall.cpp:919 main double_strands_scaling=1
= main.2 nanocall.cpp:920 main scaling_num_events=200
= main.2 nanocall.cpp:921 main scaling_max_rounds=10
= main.2 nanocall.cpp:922 main scaling_min_progress=1
= main.2 nanocall.cpp:923 main scaling_select_threshold=20
= main.2 nanocall.cpp:152 init_models loaded builtin module [t.006.ont.model] for strand [0] statistics [mean=58.1481, stdv=6.16897]
= main.2 nanocall.cpp:152 init_models loaded builtin module [c.p1.006.ont.model] for strand [1] statistics [mean=59.2641, stdv=6.23684]
= main.2 nanocall.cpp:152 init_models loaded builtin module [c.p2.006.ont.model] for strand [1] statistics [mean=60.3797, stdv=7.23367]
= main.2 nanocall.cpp:170 init_transitions init_state_transitions pr_skip=[0.3], pr_stay=[0.1]
= main.2 nanocall.cpp:208 init_files adding input file [mumgf_PC_20160914_FNFAB29733_MN17852_sequencing_run_FAB29733test7_11420_ch261_read10340_strand1.fast5]
= Fast5_Summary.2 Fast5_Summary.hpp:135 summarize mumgf_PC_20160914_FNFAB29733_MN17852_sequencing_run_FAB29733test7_11420_ch261_read10340_strand1.fast5: no eventdetection events
= main.2 nanocall.cpp:250 init_reads summary: [base_file_name=mumgf_PC_20160914_FNFAB29733_MN17852_sequencing_run_FAB29733test7_11420_ch261_read10340_strand1 valid=1 num_ed_events=0]
= main.2 Parameter_Trainer.hpp:56 init using [2160] states for state trainsition training
= main.2 nanocall.cpp:561 train_reads training user_cpu_secs=0
= main.2 nanocall.cpp:801 basecall_reads basecalling user_cpu_secs=0

Care to point out what may potentially be the problem?

Thanks

**Comment by mateidavid** [comment]
There are 2 steps from turning raw picoamp measurements into bases: event detection and event basecalling. In the past (R7.3), MinKNOW was doing "good" event detection locally on your laptop. So Nanocall never tried to replicate that part, only the actual basecalling, which used to be done in the cloud.

In short, you need to run event detection (usually by MinKNOW) before Nanocall can work. Perhaps there are alternatives out there?

With R9, there was another complication, which was that (at least for a few good months around April 2016), the event detection done locally by MinKNOW was quite bad. Metrichor in the cloud would then re-do a better event detection before basecalling. At that time, it was noticeably better to use the Metrichor event detection with Nanocall. (That's why the `--ed-group` command option was added.) I don't have data processed with most recent MinKNOW to check if the local detection has improved.

**Comment by jts** [comment]
If the MinKNOW local basecaller is run, the events will be in group `001` rather than `000`, which only contains sequence. Maybe that is what is happening here? I need to handle this situation in nanopolish and I'm not sure how yet.

**Comment by mateidavid** [comment]
The group number, such as `000` or `001`, is specific to the type of data, so I don't understand what you mean when you say that `000` only contains sequence. Eg, event detection data is in HDF5 groups such as `/Analyses/EventDetection_000/Reads/Read_399/Events`.

The more recent `fast5` versions auto-select the lowest event detection group. So, if both `/Analyses/EventDetection_000` and `/Analyses/EventDetection_001` are present, then `000` is used. If only `/Analyses/EventDetection_001` is present, it should get used without any other cl parameters.

Also, Nanocall v0.5.13 from OP is a bit old, it's only now that I noticed.

**Comment by jts** [comment]
I meant that `Basecall_1D_000/Events` doesn't exist when MinKNOW basecalling is enabled (you get `Basecall_1D_000/Fastq` and when you run Metrichor you get `Basecall_1D_001/Events`). If you use `get_basecall_groups()` in `fast5` you will get back both `000` and `001` but only `001` contains events, which is the problem in nanopolish. I guess since you use `*EventDetection* it is not an issue for nanocall.

**Comment by mht85** [comment]
Thanks for your replies, appreciate it very much. It's strange because all the fast5 files I got from MinKNOW do not contain Event information at all - this was checked using HDFview. Is there a specific step or setting that controls event detection in MinKNOW?
