### ISSUE TITLE
Missing R9 parameter files

### ISSUE THREAD

**Issue by tvinar** [mateidavid/nanocall#11]
R9 parameter files seem to be missing. Could you please add them?

**Comment by mateidavid** [comment]
I'm not sure I understand- Are you getting a build or a runtime error with Nanocall?

In case you mean that the raw R9 model files are missing- I didn't include them on purpose, instead I baked them into array initializers in those `.inl` files. (I chose that because at the time, I wasn't sure what ONT's position was about including them in an external tools.) The `.inl` files should be enough to build Nanocall. If you want the raw model files, you can try getting them through the ONT wiki, or you could easily reverse engineer the Nanocall code that reads the `.inl` files [here](https://github.com/mateidavid/nanocall/blob/master/src/nanocall/Pore_Model.hpp#L221).

**Comment by mateidavid** [comment]
These seem to be public these days: https://github.com/nanoporetech/kmer_models .
