### ISSUE TITLE
R9.4 compatible?

### ISSUE THREAD

**Issue by alantsangmb** [mateidavid/nanocall#12]
Hello Dr. David.
Glad to see there is a local basecalling tool for nanopore.
I have a question rather than an issue.
As the latest Minion flow cell is R9.4 (SQK-SK208).

Is nanocall compatible for this 2D sequencing data?
Thanks.

**Comment by mateidavid** [comment]
Nanocall includes R9 pore models, and it uses them by default today, unless `--pore r73` is explicitly specified. That being said, these days (since Aug 2016 to be exact), ONT provide a local basecaller a part of MinKNOW:
https://nanoporetech.com/about-us/news/local-basecalling-now-available-enabling-minion-usage-field
https://community.nanoporetech.com/posts/minknow-1-0-2-local-base (for ONT community members)

This MinKNOW basecaller only produces 1D reads, but it uses a more elaborate RNN framework instead of the simpler HMM used by Nanocall. Moreover, the MinKNOW basecaller is fully supported by ONT, so you can expect it to be updated as needed. If your primary concern is local basecalling, I suggest you try that option before falling back to Nanocall.

When we wrote Nanocall, there was no local alternative, but these days there is. As a result, I think you should primarily use Nanocall as a base for further development, or in situations where, for various reasons, you do not have access to (or you are specifically trying to avoid) the MinKNOW local basecaller.
