### ISSUE TITLE
missing eventdetection events when calling on raw reads (uploaded folder)

### ISSUE THREAD

**Issue by danarte** [mateidavid/nanocall#13]
Hi, The issue might be that I dont understand the correct usage of the program and I would gladly accept your guidance.
Anyway, when I try to use nanocall on the uploaded folder (which contains .fast5 files with only raw signal) I get empty fasta files from nanocall output. The error output shows this:
```
= main.2 nanocall.cpp:270 init_reads summary: [base_file_name=MinION_PC_20160907_FNFAD12322_MN19084_mux_scan_Lambda_Burn_In_Library1_51105_ch227_read31_strand valid=1 num_ed_events=0]
= Fast5_Summary.2 Fast5_Summary.hpp:176 summarize /genomicslab/nobackup/volume2/artemd/minion/third_lambda_run/reads/uploaded/MinION_PC_20160907_FNFAD12322_MN19084_mux_scan_Lambda_Burn_In_Library1_51105_ch303_read66_strand.fast5: missing eventdetection events

```
This is shown for every read which is processed.

I was able to run nanocall on reads from both the fail and pass folder, but those reads were processed by metrichore which contradicts the aim of this software to be an alternative basecaller. I'm almost certain that some crucial information went over my head and I would be happy if you could explain me what is I'm missing.

ps: another small question, as I understand the only available output format is fasta? which means the quality of bases/reads is "thrown away"?

**Comment by mateidavid** [comment]
I've added an explanation in the main README about the role of Nanocall with respect to R7.3/R9, and the various levels of ONT sequencing data.

In short:
1. Make sure you really need Nanocall on recent R9 data.
2. If you do, Nanocall needs events, not raw samples. On R9, either MinKNOW or Metrichor must be used to generate them.

The apparent contradiction is due to the changes in ONT software. On R7.3, event detection was performed locally and reliably by MinKNOW, so we never tried to redo it as part of Nanocall.

Regarding qvs, ONT data in general is way too noisy (compared to Illumina) for qvs to be useful. Even with Metrichor, the error rate is ~10%, which means most qvs would be 1.
