### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by hsnguyen** [mateidavid/nanocall#3]
Hi,
I have nanocall installed as guided and now trying to run on our data. But then the 'core dumped' error appeared with a warning about it:

> The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.14, library is 1.8.16

Attached are the full output log.
[log.txt](https://github.com/mateidavid/nanocall/files/274244/log.txt)

**Comment by mateidavid** [comment]
The log is very explicit about what is going on: there is a mismatch between hdf5 headers and libraries. What `cmake` command line did you use to configure the build?

**Comment by hsnguyen** [comment]
I used the exact same `cmake` as recommended:
`cmake ../src -DCMAKE_INSTALL_PREFIX=/some/install/dir -DBUILD_HDF5=1 `

I've made some changes in CMakeList.txt for the right link to hdf5 1.8.16 (the current version is 1.8.17).
So how can I match the header with the library?

**Comment by mateidavid** [comment]
Ok, I fixed the link. Can you check there are no other changes to your CMakeLists.txt? The problem is that for whatever reason 1.8.14 interferes with 1.8.16, which is the version downloaded by Nanocall. Perhaps 1.8.14 is installed in a system directory and somehow the include paths are not set up properly? Note that the message is unclear whether the problem is with the nanocall executable or with the libhdf5.a library.

To diagnose this, create a new build tree, and add `-DCMAKE_BUILD_TYPE=Test` to the `cmake` command line. This will switch to a `Test` build, as opposed to a `Release` build. As a side effect, you will get to see all `gcc` commands that are being run. To log what's going on, use e.g. `script -c make make.log`. This will run `make` and dump everything it does into `make.log`.

To check which hdf5 headers `gcc` uses by default, use: `echo "#include <H5version.h>" | gcc -v -x c++ -E -`. Among other things, it will contain something like: `# 1 "/usr/local/include/H5version.h" 1 3`, telling you by default `gcc` uses the hdf5 headers in `/usr/local/include`.

Once nanocall is built, try to run `h5dump` from the `src/optional/bin` subdirectory on a fast5 file. This is the newly build hdf5. If it works, we know at least the hdf library is ok, and the error is with nanocall. If it doesn't work, the problem is with the newly build libhdf5.

**Comment by hsnguyen** [comment]
The command `echo "#include <H5version.h>" | gcc -v -x c++ -E -`
hasn't returned any hit. Seems like there is no hdf5 being install in my system previously. And I have `h5dump` working fine.
Anyway, I again changed the link of hdf5 version down to 1.8.14 hoping it would match the somewhere header. The warning has gone but another issue rising when I test `nanocal` with a single fast5 file (attached):

>  = main.2 nanocall.cpp:846 main program: nanocall
> = main.2 nanocall.cpp:847 main version: v0.5.11
> = main.2 nanocall.cpp:848 main args: /home/s.hoangnguyen/soft/Basecalling/GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file12_strand.fast5
> = main.2 nanocall.cpp:849 main num_threads=1
> = main.2 nanocall.cpp:911 main train=1
> = main.2 nanocall.cpp:914 main only_train=0
> = main.2 nanocall.cpp:915 main train_scaling=1
> = main.2 nanocall.cpp:916 main train_transitions=1
> = main.2 nanocall.cpp:919 main double_strands_scaling=1
> = main.2 nanocall.cpp:920 main scaling_num_events=200
> = main.2 nanocall.cpp:921 main scaling_max_rounds=10
> = main.2 nanocall.cpp:922 main scaling_min_progress=1
> = main.2 nanocall.cpp:923 main scaling_select_threshold=20
> = main.2 nanocall.cpp:152 init_models loaded builtin module [t.006.ont.model] for strand [0] statistics [mean=58.1481, stdv=6.16897]
> = main.2 nanocall.cpp:152 init_models loaded builtin module [c.p1.006.ont.model] for strand [1] statistics [mean=59.2641, stdv=6.23684]
> = main.2 nanocall.cpp:152 init_models loaded builtin module [c.p2.006.ont.model] for strand [1] statistics [mean=60.3797, stdv=7.23367]
> = main.2 nanocall.cpp:170 init_transitions init_state_transitions pr_skip=[0.3], pr_stay=[0.1]
> = main.2 nanocall.cpp:208 init_files adding input file [/home/s.hoangnguyen/soft/Basecalling/GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file12_strand.fast5]
> HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140149003609920:
>   #000: H5A.c line 1672 in H5Aexists_by_name(): unable to determine if attribute exists
>     major: Attribute
>     minor: Can't get value
>   #001: H5Aint.c line 1210 in H5A_exists_by_name(): object not found
>     major: Attribute
>     minor: Object not found
>   #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
>     major: Symbol table
>     minor: Object not found
>   #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
>     major: Symbol table
>     minor: Object not found
>   #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
>     major: Symbol table
>     minor: Object not found
> = main.1 Fast5_Summary.hpp:243 summarize /home/s.hoangnguyen/soft/Basecalling/GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file12_strand.fast5: HDF5 error: /UniqueGlobalKey/channel_id/channel_number: error in H5Aexists_by_name
> = main.2 nanocall.cpp:250 init_reads summary: [base_file_name=imb13-010577-lt_GN_045_0428_1_ch100_file12_strand valid=1 num_ed_events=0]
> = main.2 Parameter_Trainer.hpp:56 init using [2160] states for state trainsition training
> = main.2 nanocall.cpp:561 train_reads training user_cpu_secs=0
> = main.2 nanocall.cpp:801 basecall_reads basecalling user_cpu_secs=0
> 
Any suggestion? 
[imb13-010577-lt_GN_045_0428_1_ch100_file12_strand.fast5.zip](https://github.com/mateidavid/nanocall/files/276812/imb13-010577-lt_GN_045_0428_1_ch100_file12_strand.fast5.zip)

**Comment by mateidavid** [comment]
I can provide support with the master branch of Nanocall. If you want to try newer (1.8.17) or older (1.8.14) hdf releases, I cannot help with that. Please use a clean source tree, a non-existing build tree, and the Nanocall master branch. Assuming you're still getting the original error message (headers 1.8.14 / libraries 1.8.16)...

If there is no system-wide 1.8.14, then where does it come from? Did you install it alongside 1.8.16 by mistake? Nanocall should only ever download 1.8.16. Assuming `h5dump` from 1.8.16 works fine, then the problem must be with the nanocall compilation line, because it is the only one that looks at hdf5 header files. You can find it in `make.log` (produced by `script` command mentioned above) by `grep -- "-o CMakeFiles/nanocall.dir/nanocall.cpp.o" make.log`.

Extract the compilation line, then add `-v -E |& awk '$0~/^#include/ {s=1;next} $0~/^End of search list/ {s=0} {if(s) print}' >include-dir-list.txt` at the end. This should dump the include search list in `include-dir-list.txt`. Look for which folder contains which hdf headers with: `for f in $(cat include-dir-list.txt); do g=$f/H5pubconf.h; [ -r $g ] || continue; echo "===== $g"; grep H5_VERSION $g; done`.

**Comment by hsnguyen** [comment]
Thanks David, that's very helpful. I fixed the version conflicted problem already but the same error still showed up when I tried to test `nanocall` with any single pre-Metrichor fast5 file.

> = main.2 nanocall.cpp:846 main program: nanocall
> = main.2 nanocall.cpp:847 main version: 0.5.13
> = main.2 nanocall.cpp:848 main args: ../../GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file30_strand.fast5
> = main.2 nanocall.cpp:849 main num_threads=1
> = main.2 nanocall.cpp:911 main train=1
> = main.2 nanocall.cpp:914 main only_train=0
> = main.2 nanocall.cpp:915 main train_scaling=1
> = main.2 nanocall.cpp:916 main train_transitions=1
> = main.2 nanocall.cpp:919 main double_strands_scaling=1
> = main.2 nanocall.cpp:920 main scaling_num_events=200
> = main.2 nanocall.cpp:921 main scaling_max_rounds=10
> = main.2 nanocall.cpp:922 main scaling_min_progress=1
> = main.2 nanocall.cpp:923 main scaling_select_threshold=20
> = main.2 nanocall.cpp:152 init_models loaded builtin module [t.006.ont.model] for strand [0] statistics [mean=58.1481, stdv=6.16897]
> = main.2 nanocall.cpp:152 init_models loaded builtin module [c.p1.006.ont.model] for strand [1] statistics [mean=59.2641, stdv=6.23684]
> = main.2 nanocall.cpp:152 init_models loaded builtin module [c.p2.006.ont.model] for strand [1] statistics [mean=60.3797, stdv=7.23367]
> = main.2 nanocall.cpp:170 init_transitions init_state_transitions pr_skip=[0.3], pr_stay=[0.1]
> = main.2 nanocall.cpp:208 init_files adding input file [../../GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file30_strand.fast5]
> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139634734778176:
>   #000: H5A.c line 1692 in H5Aexists_by_name(): unable to determine if attribute exists
>     major: Attribute
>     minor: Can't get value
>   #001: H5Aint.c line 1200 in H5A_exists_by_name(): object not found
>     major: Attribute
>     minor: Object not found
>   #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
>     major: Symbol table
>     minor: Object not found
>   #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
>     major: Symbol table
>     minor: Object not found
>   #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
>     major: Symbol table
>     minor: Object not found
> = main.1 Fast5_Summary.hpp:243 summarize ../../GN045_R7/imb13-010577-lt_GN_045_0428_1_ch100_file30_strand.fast5: HDF5 error: /UniqueGlobalKey/channel_id/channel_number: error in H5Aexists_by_name
> = main.2 nanocall.cpp:250 init_reads summary: [base_file_name=imb13-010577-lt_GN_045_0428_1_ch100_file30_strand valid=1 num_ed_events=0]
> = main.2 Parameter_Trainer.hpp:56 init using [2160] states for state trainsition training
> = main.2 nanocall.cpp:561 train_reads training user_cpu_secs=0
> = main.2 nanocall.cpp:801 basecall_reads basecalling user_cpu_secs=0

Seems like some fields are missing in the file but needed in your program. As far as I know, the raw reads contain nothing but the signal.
Btw, test for a post-Metrichor read is OK.

**Comment by mateidavid** [comment]
I pushed a new version which is more explicit about what is happening in this case. Specifically, here are some differences between the pre-Metrichor file you tried and what Nanocall expects:
- your file: the sampling rate is missing; expected at: `/UniqueGlobalKey/channel_id/sampling_rate`
- your file: `channel_id` subgroup mentioned above is missing altogether; expected: subgroup of `/UniqueGlobalKey`
- your file: evendetection events under `/Reads/Read_12/Events`; expected: eventdetection events under `/Analyses/EventDetection_*/Reads/Read_*/Events`

The message you were seeing was caused by Nanocall expecting fast5 files to always contain the sampling rate, which is apparently false(!?)

I am not sure where this type of inconsistencies come from. It could be an issue with your MinKNOW configuration, or it could just be ONT changing the inner fast5 format. Unfortunately, they don't have a formal fast5 spec, so it is a moving target for us. The fast5 subproject is dealing with these issues, which I'm also maintaining.

For now, I made Nanocall print an explicit message about why it is discarding the file ("missing sampling rate"). The previous version was also discarding the file and continuing, just that you'd see the inner hdf5 exception in the log. If other people complain about this, I'll assume ONT changed the spec and I'll update fast5 accordingly.
